### PR TITLE
Update 42.cpp

### PR DESCRIPTION
**Pull request by Wa-wann**
Your code has some error and I tried to rebuild it with rules in readme.

### CODE REVIEW

**Comment by ayan-b** [comment]
Can you please specify where the error is. Also remember we are least concerned about how the integers are stored etc., we just take the output into account.

**Comment by Wa-wann** [comment]
I'm a begginer I probably made mistakes but when I tried to compile your program (/cpp/42.cpp) it gave me some errors (as you can see).
screen
So I tried to solve the problem from scratch.

**Comment by ayan-b** [comment]
Actually this is an accepted-solution-code, maybe we are using different compiler.

**Comment by Nurrl** [comment]
@Wa-wann I like your Atom theme, what is it ?

**Comment by Wa-wann** [comment]
My UI theme is One Light and my syntax theme is one light too.

**Comment by Nurrl** [comment]
Thanks ^^ @Wa-wann

**Pull request merged**
